FROM node:bullseye-slim
ENV NODE_VERSION 22.8.0

LABEL description="SoilFlo Interview Take Home API"

WORKDIR /usr/src/soilflo

COPY package*.json ./

RUN npm install

COPY ./tsconfig.json ./
COPY src/common ./src/common
COPY src/soilflo ./src/soilflo
COPY ./data/*.json ./data/

RUN npm install -g typescript

RUN npm run build
RUN ls -al dist

CMD ["node", "dist/soilflo/app.js"]
